[package]
name = "changelog-generator"
version = "0.1.0"
edition = "2021"
rust-version = "1.64.0"

[dependencies]
clap = { version= "4.0.18", features = ["derive"] }
walkdir = "2.3.2"

[build.env]
passthrough = [
  "RUSTFLAGS"
]
